### ISSUE TITLE
Repo encoding crash (actually in python-anyvcs)

### ISSUE THREAD

**Issue by OEP** [ClemsonSoCUnix/django-anyvcs#14]
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 371, in inner
    return func(_args, *_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/buffet/core/decorators.py", line 22, in _wrapped_view
    return view_func(request, _args, *_kw)

  File "/usr/local/lib/python2.7/dist-packages/buffet/vcs/views.py", line 111, in _wrapped_view
    return view_func(request, username, resource_name, _args, *_kw)

  File "/usr/local/lib/python2.7/dist-packages/buffet/vcs/views.py", line 259, in repo_commit_detail
    diff += client.diff(entry.parents[0], rev, info.path)

  File "/usr/local/lib/python2.7/dist-packages/anyvcs/git.py", line 350, in diff
    return self._command(cmd).decode(self.encoding)

  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xb2 in position 424: invalid start byte

---
- Bitbucket: https://bitbucket.org/OEP/ClemsonSoCUnix/django-anyvcs/issue/14
- Originally reported by: Chuck Cook
- Originally created at: 2015-04-20T20:15:24.650

**Comment by OEP** [comment]
Here's some additional email from the Django notification email:

```
#!XML

<WSGIRequest
path:/vcs/u/tscott2/cpsc822-proj3/commits/rev/744d38ab7b51a30b676ae0550995374b5871ed26/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'auCgQ4GMTJ0N8HvtW7MQ5gNBLFhG1YSb',
 'sessionid': 'x6vztmkf1v9eeybj6no4lrah94bmdk0w'},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 u'CSRF_COOKIE': u'auCgQ4GMTJ0N8HvtW7MQ5gNBLFhG1YSb',
 'DOCUMENT_ROOT': '/usr/share/nginx/html',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'csrftoken=auCgQ4GMTJ0N8HvtW7MQ5gNBLFhG1YSb; sessionid=x6vztmkf1v9eeybj6no4lrah94bmdk0w',
 'HTTP_HOST': 'buffet.cs.clemson.edu',
 'HTTP_REFERER': 'https://buffet.cs.clemson.edu/vcs/u/tscott2/cpsc822-proj3/commits/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0',
 'PATH_INFO': u'/vcs/u/tscott2/cpsc822-proj3/commits/rev/744d38ab7b51a30b676ae0550995374b5871ed26/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '2620:103:a000:401:9df4:65ca:679:ac8d',
 'REMOTE_PORT': '39030',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/vcs/u/tscott2/cpsc822-proj3/commits/rev/744d38ab7b51a30b676ae0550995374b5871ed26/',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'buffet.cs.clemson.edu',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'UWSGI_SCHEME': 'https',
 'uwsgi.node': 'buffet1.cs.clemson.edu',
 'uwsgi.version': '1.9.17.1-debian',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f09d94774b0>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f09ccd06f30>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>
```

---

Original comment by: Chuck Cook

**Comment by OEP** [comment]
This may actually be [issue 72](https://bitbucket.org/ClemsonSoCUnix/django-buffet/issue/72/encoding-issues) over in django-buffet. I think it is Buffet's responsibility to catch the encoding error.

---

Original comment by: Paul Kilgo

**Comment by OEP** [comment]
Yeah, that makes sense. If Buffet is tying to use the library it should handle the error properly.

---

Original comment by: Chuck Cook

**Comment by OEP** [comment]
Exception should be handled by Buffet.

---

Original comment by: Chuck Cook
